app/models.py
"""
Python Datastore API: http://code.google.com/appengine/docs/python/datastore/
"""

from google.appengine.ext import db


class Todo(db.Model):
    """Model to save a Todo to the GAE Datastore."""
    text = db.StringProperty()
    created_at = db.DateTimeProperty(auto_now_add=True)

app/forms.py
"""
WTForms Documentation:    http://wtforms.simplecodes.com/
Flask WTForms Patterns:   http://flask.pocoo.org/docs/patterns/wtforms/
Flask-WTF Documentation:  http://packages.python.org/Flask-WTF/

Forms for your application can be stored in this file.
"""

from flaskext.wtf import (Form, TextField, TextAreaField, SubmitField,
                          Required, Email)


class TodoForm(Form):
    """Simple todo form."""
    todo = TextField(validators=[Required()])
    submit = SubmitField("add")


class EmailForm(Form):
    """Simple email form."""
    name = TextField("Your Name", validators=[Required()])
    recipient = TextField("Recipient's Email", validators=[Email()])
    email = TextField("Your Email", validators=[Email()])
    message = TextAreaField("Message", validators=[Required()])
    submit = SubmitField("Send Email")

app/__init__.py
"""
Flask Documentation:       http://flask.pocoo.org/docs/
Jinja2 Documentation:      http://jinja.pocoo.org/2/documentation/
Werkzeug Documentation:    http://werkzeug.pocoo.org/documentation/
GAE Python Documentation:  http://code.google.com/appengine/docs/python/

This file creates your application.
"""

from flask import Flask
from views import views
import settings


def create_app():
    """
    Create your application. Files outside the app directory can import
    this function and use it to recreate your application -- both
    bootstrap.py and the `tests` directory do this.
    """
    app = Flask(__name__)
    app.config.from_object(settings)
    app.register_blueprint(views)
    return app

app/views.py
"""
Flask Module Docs:  http://flask.pocoo.org/docs/api/#flask.Module

This file is used for both the routing and logic of your
application.
"""

from google.appengine.api import mail

from flask import Blueprint, url_for, render_template, request, redirect
from models import Todo
from forms import TodoForm, EmailForm

views = Blueprint('views', __name__)


@views.route('/')
def index():
    """Render website's index page."""
    return render_template('index.html')


@views.route('/todo/')
def todo_list():
    """Simple todo page."""
    form = TodoForm()
    todos = Todo.all().order('-created_at')
    return render_template('todo.html', form=form, todos=todos)


@views.route('/todo/add', methods=["POST"])
def add_todo():
    """Add a todo."""
    form = TodoForm()
    if request.method == 'POST' and form.validate_on_submit():
        todo = Todo(text=form.todo.data)
        todo.save()
    return redirect(url_for('todo_list'))


@views.route('/email/')
def email():
    """Render a form for sending email."""
    form = EmailForm()
    return render_template('email.html', form=form)


@views.route('/email/someone/', methods=['POST'])
def email_someone():
    """
    This function actually emails the message.

    Make sure you change the from_address variable if you want to use this
    functionality -- otherwise it won't work.
    """
    form = EmailForm()
    if request.method == 'POST' and form.validate_on_submit():
        from_address = form.name.data + '@<YOURAPPID>.appspotmail.com'
        to_address = form.recipient.data
        subject = "%s <%s>" % (form.name.data, form.email.data)
        message = ("From: %s\n\n"
                   "Email: %s\n\n"
                   "Message: %s") % (form.name.data, form.email.data,
                                     form.message.data)
        mail.send_mail(sender=from_address, to=to_address,
                       subject=subject, body=message)
        status = 'success'
    else:
        status = 'failed'
    return redirect(url_for('email_status', status=status))


@views.route('/email/<status>/')
def email_status(status):
    """Render a success or failed status for the email."""
    return render_template('email_status.html', status=status)


@views.route('/qunit/')
def qunit():
    """Render a QUnit page for JavaScript tests."""
    return render_template('test_js.html')


@views.after_request
def add_header(response):
    """Add header to force latest IE rendering engine and Chrome Frame."""
    response.headers['X-UA-Compatible'] = 'IE=Edge,chrome=1'
    return response


@views.app_errorhandler(404)
def page_not_found(error):
    """Custom 404 page."""
    return render_template('404.html'), 404

app/templates/_form_helpers.html
{% macro render_field(field) %}
<p>
  {{ field.label }}
  <br />
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
  <br />
    <ul class="errors">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</p>
{% endmacro %}

app/templates/base.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block title %}gae-flask-html5{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  <!-- CSS: implied media="all" -->
  <link rel="stylesheet" href="/css/style.css?v=2">
  {% block css %}{% endblock %}

  <!-- Uncomment if you are specifically targeting less enabled mobile browsers
  <link rel="stylesheet" media="handheld" href="/css/handheld.css?v=2">  -->

  <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
  <script src="/js/libs/modernizr-1.7.min.js"></script>

</head>

<body>

  <div id="container">
    <header>
      {% block header %}{% endblock %}
    </header>
    <div id="main" role="main">
      {% block main %}{% endblock %}
    </div>
    <footer>
      {% block footer %}{% endblock %}
    </footer>
  </div> <!--! end of #container -->

  <a href="http://github.com/zachwill/gae-flask-html5">
    <img style="position: absolute; top: 0; right: 0; border: 0;"
    src="/img/github_ribbon.png" alt="Fork me on GitHub">
  </a>

  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.5.1.min.js">\x3C/script>')</script>

  {% block js %}{% endblock %}


  <!--[if lt IE 7 ]>
    <script src="/js/libs/dd_belatedpng.js"></script>
    <script>DD_belatedPNG.fix('img, .png_bg'); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
  <![endif]-->


  <!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>

</body>
</html>

app/templates/email.html
{% extends "base.html" %}


{% block title %}ohai email{% endblock %}


{% block css %}
<link rel="stylesheet" href="/css/formalize.css">
<style>
    .link{
        font-size:20px;
        text-align:center;
    }
    h1{
        font-size:36px;
        margin:50px 0;
        text-align:center;
    }
    em{
        display:block;
        font-size:14px;
        text-align:center;
    }
    form{
        margin:50px auto;
        width:600px;
    }
    p{
        margin:15px 5px;
    }
    input[type="text"], textarea{
        font-size:16px;
        margin:5px 0;
        padding:5px;
        width:100%;
    }
    label{
        text-transform:uppercase;
    }
    input[type="submit"]{
        display:block;
        margin:0 auto;
        width:100px;
    }
</style>
{% endblock %}


{% block js %}
<script src="/js/jquery.formalize.min.js" type="text/javascript"></script>
{% endblock %}


{% block main %}
<p class="link"><a href="{{ url_for('views.index') }}">&larr; go back home</a></p>
<h1>send an email to someone</h1>
<em>NOTE: you'll have to change the <code>from_address</code> to your app's ID
    in <code>views.py</code></em>

{% from "_form_helpers.html" import render_field %}
<form action="{{ url_for('views.email_someone') }}" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, placeholder="Your Name") }}
    {{ render_field(form.email, placeholder="email@your-email.com") }}
    {{ render_field(form.recipient, placeholder="recipient@their-email.com") }}
    {{ render_field(form.message, placeholder="I'm emailing you because...",
        rows=8) }}
    {{ form.submit }}
</form>
{% endblock %}

app/templates/email_status.html
{% extends "base.html" %}


{% block title %}email status{% endblock %}

{% block css %}
<style>
    p{
        font-size:24px;
        text-align:center;
    }
    .headline{
        margin:50px 0 75px;
    }
    h1{
        font-size:36px;
        margin:20px 0;
        text-align:center;
    }
</style>
{% endblock %}

{% block main %}
<p class="headline"><a href="{{ url_for('views.index') }}">&larr; go back home</a> or
<a href="{{ url_for('views.email') }}">send another email &rarr;</a></p>

{% if status == 'success' %}
<p>Your email was a...<p>
<h1>{{ status|title }}.</p>

{% else %}
<p>Sorry about that. Looks like your email...</p>
<h1>{{ status|title }}.</h1>

{% endif %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}ohai html5 boilerplate{% endblock %}

{% block css %}
<style>
    h1{
        font-size:48px;
        margin:75px 0 50px;
        text-align:center;
    }
    p{
        font-size:20px;
        margin:25px 0;
        text-align:center;
    }
    strong{
        font-size:24px;
    }
</style>
{% endblock %}


{% block main %}
<h1>ohai</h1>
<p><strong>I'm in yo app-engine &mdash; html5 boilerplatin' it up</strong></p>
<p>Now why don't you go <a href="{{ url_for('views.todo_list') }}">check what you need todo?</a></p>
<p>Or <a href="{{ url_for('views.email') }}">send an email</a> to someone you know?</p>
<p>Or check that your <a href="{{ url_for('views.qunit') }}">JavaScript tests pass QUnit?</a></p>
<p>You could always check your <a href="/asdf">custom 404 page</a>, too.</p>
{% endblock %}

app/templates/qunit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}QUnit Tests{% endblock %}</title>
  <link rel="stylesheet" href="/css/qunit.css" media="screen">
  {% block css %}{% endblock %}
<!-- reference your own javascript files here -->
  {% block js %}{% endblock %}

<!-- test runner files -->
  <script src="/js/qunit/qunit.js"></script>
  
  {% block test_js %}{% endblock %}

</head>
<body class="flora">
  <h1 id="qunit-header">QUnit Test Suite</h1>
  <h2 id="qunit-banner"></h2>
  <div id="qunit-testrunner-toolbar"></div>
  <h2 id="qunit-userAgent"></h2>
  <ol id="qunit-tests"></ol>
  <div id="qunit-fixture">test markup</div>
  </body>
</html>

app/templates/test_js.html
{% extends "qunit.html" %}

{% block js %}
  <script src="/js/libs/modernizr-1.7.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script> 
  <script src="/js/plugins.js"></script> 
{% endblock %}


{% block test_js %}
  <script src="/js/tests.js"></script>
{% endblock %}

app/templates/todo.html
{% extends "base.html" %}

{% block title %}ohai todo{% endblock %}

{% block css %}
<link rel="stylesheet" href="/css/formalize.css">
<style>
    p{
        font-size:20px;
        margin:10px 0;
        text-align:center;
    }
    h1{
        font-size:48px;
        margin:75px 0 25px;
        text-align:center;
    }
    div.center{
        width:600px;
        margin:0 auto;
    }
    input[type="text"]{
        font-size:20px;
        padding:5px;
        width:500px;
    }
    input[type="submit"]{
        margin:0 5px;
        padding:5px 10px;
    }
    ul{
        margin:25px auto 0;
        width:600px;
    }
    li{
        padding:5px;
    }
</style>
{% endblock %}


{% block header %}
<p><a href="{{ url_for('views.index') }}">&larr; go back home</a></p>
{% endblock %}


{% block main %}
<h1>some todos</h1>
<div class="center">
  <form action="{{ url_for('views.add_todo') }}" method="post">
      {{ form.hidden_tag() }}
      {{ form.todo(placeholder="write your todo here") }}
      {{ form.submit }}
  </form>
</div>

<ul id="todos">
  {% for todo in todos %}
    <li>{{ todo.text }}</li>
  {% endfor %}
</ul>

{% endblock %}


{% block js %}
<script src="/js/jquery.formalize.min.js" type="text/javascript"></script>
<script type="text/javascript">

  (function(){

    var num = $('ul').children().length,
        form = $('form');

    if(num === 0){
      $('input[type="text"]').val('read the source code, luke');
    }

    form.submit(function(e){
      var add = $('input[type="submit"]'),
          container = $('#container');

      add.attr('disabled', true);

      container.load(
        form.attr('action') + '#todos',
        form.serializeArray(),
        function(response, status){
          $('input[type="submit"]').attr('disabled', false);
        });

      e.preventDefault();

    });

  })();

</script>
{% endblock %}